# Generated by Django 4.2.1 on 2023-05-15 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('raterprojectapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='game_category',
            field=models.ManyToManyField(null=True, to='raterprojectapi.game'),
        ),
        migrations.AlterField(
            model_name='game',
            name='estimated_time',
            field=models.DurationField(),
        ),
    ]
