# Generated by Django 4.2.1 on 2023-05-16 20:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raterprojectapi', '0002_player_user_alter_category_game_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='year_released',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1500), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
